import zlib

ARCConstants = {
    "ARC_META_CHARSET": "utf-8",
    "NEW_LINE_ORD": 10,
    "CARRIAGE_RETURN_ORD": 13,
    "String DELIMITER": " ",
    "FIELD_COUNT": 5,
    "URL_KEY": "Target-URI",
    "IP_KEY": "IP-Address",
    "DATE_STRING_KEY": "Date",
    "MIME_KEY": "Content-Type",
    "DECLARED_LENGTH_KEY": "Content-Length",
    "ACTUAL_LENGTH_KEY": "Actual-Length",
    "LEADING_NEWLINES_KEY": "Leading-Newlines",
    "TRAILING_NEWLINES_KEY": "Trailing-Newlines",
    "TRAILING_CRUFT_KEY": "Trailing-Slop",
    "HEADER_LENGTH": "Header-Length",
    "DEFAULT_MIME": "x-archive/unknown",
    "FILEDESC_SCHEME": "filedesc:/",
    "DNS_MIME": "text/dns",
    "ALEXA_DAT_MIME": "alexa/dat",
    "DEFAULT_MAX_ARC_FILE_SIZE": 100000000,
    "MAX_METADATA_LINE_LENGTH": 4096,
    "ARC_FILE_EXTENSION": "arc",
    "DOT_ARC_FILE_EXTENSION": ".arc",
    "DOT_COMPRESSED_FILE_EXTENSION": ".gz",
    "COMPRESSED_ARC_FILE_EXTENSION": "arc.gz",
    "DOT_COMPRESSED_ARC_FILE_EXTENSION": ".arc.gz",
    "DEFAULT_ENCODING": "ISO-8859-1",
    "LINE_SEPARATOR": '\n',
    "ARC_MAGIC_NUMBER": "filedesc://",
    "HEADER_FIELD_SEPARATOR": ' ',
    "ARC_GZIP_EXTRA_FIELD": bytes([8, 0, 'L', 'X', 4, 0, 0, 0, 0, 0]),
    "IP_HEADER_FIELD_KEY": "ip-address",
    "CODE_HEADER_FIELD_KEY": "result-code",
    "CHECKSUM_HEADER_FIELD_KEY": "checksum",
    "LOCATION_HEADER_FIELD_KEY": "location",
    "OFFSET_HEADER_FIELD_KEY": "offset",
    "FILENAME_HEADER_FIELD_KEY": "filename",
    "STATUSCODE_FIELD_KEY": "statuscode",
    "OFFSET_FIELD_KEY": "offset",
    "FILENAME_FIELD_KEY": "filename",
    "CHECKSUM_FIELD_KEY": "checksum",
    "TOKENIZED_PREFIX": "tokenized_",
    "MAX_HEADER_LINE_LENGTH": 102400,
    "REQUIRED_VERSION_1_HEADER_FIELDS": ["subject-uri", "ip-address", "creation-date", "content-type", "length",
                                         "version", "origin", "absolute-offset"],
    "MINIMUM_RECORD_LENGTH": 1 + len("://") + 1 + len("arc") + len(" ") + 1 + len(" ")
                             + 1 + len(" ") + 1 + len("/") + 1 + len(" ") + 1,
    "GZIP_HEADER_BEGIN": bytes([0x1f, 0x8b, zlib.DEFLATED]),
    "DEFAULT_GZIP_HEADER_LENGTH": 10,
    "ArcRecordErrors": ["HTTP_HEADER_TRUNCATED", "HTTP_STATUS_LINE_INVALID", "HTTP_STATUS_LINE_EXCEPTION"]
}
