WARCConstants = {
    "INVALID_SUFFIX": ".invalid",
    "DOT_COMPRESSED_FILE_EXTENSION": ".gz",
    "VERSION_FIELD_KEY": "version",
    "ORIGIN_FIELD_KEY": "origin",
    "LENGTH_FIELD_KEY": "length",
    "TYPE_FIELD_KEY": "type",
    "URL_FIELD_KEY": "subject-uri",
    "DATE_FIELD_KEY": "creation-date",
    "MIMETYPE_FIELD_KEY": "content-type",
    "RECORD_IDENTIFIER_FIELD_KEY": "record-identifier",
    "ABSOLUTE_OFFSET_KEY": "absolute-offset",
    "READER_IDENTIFIER_FIELD_KEY": "reader-identifier",
    "CDX_LINE_BUFFER_SIZE": 14 + 1 + 15 + 1 + 1024 + 1 + 24 + 1 + 3 + 1 + 32 + 1 + 20 + 1 + 20 + 1 + 64,
    "DEFAULT_DIGEST_METHOD": "SHA-1",
    "SINGLE_SPACE": " ",
    "CRLF": "\r\n",
    "CDX": "cdx",
    "DUMP": "dump",
    "GZIP_DUMP": "gzipdump",
    "HEADER": "header",
    "NOHEAD": "nohead",
    "CDX_FILE": "cdxfile"
}